; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 20 2020 10:34:10 GMT+0300 (RTZ 2 (зима))
; ================================================================================

DATAQP5EZUDB6I:
	dc.w DATAQP5EZUDB6I_0-DATAQP5EZUDB6I, DATAQP5EZUDB6I_1-DATAQP5EZUDB6I
	dc.w DATAQP5EZUDB6I_2-DATAQP5EZUDB6I, DATAQP5EZUDB6I_3-DATAQP5EZUDB6I
	dc.w DATAQP5EZUDB6I_4-DATAQP5EZUDB6I, DATAQP5EZUDB6I_5-DATAQP5EZUDB6I
	dc.w DATAQP5EZUDB6I_6-DATAQP5EZUDB6I, DATAQP5EZUDB6I_7-DATAQP5EZUDB6I
	dc.w DATAQP5EZUDB6I_8-DATAQP5EZUDB6I
DATAQP5EZUDB6I_0: dc.b $2
	dc.b $F8, $C, $20, $0, $F0
	dc.b $0, $4, $20, $4, $F8
DATAQP5EZUDB6I_1: dc.b $1
	dc.b $0, $C, $20, $0, $F0
DATAQP5EZUDB6I_2: dc.b $2
	dc.b $E8, $C, $20, $0, $F0
	dc.b $F0, $6, $20, $6, $F8
DATAQP5EZUDB6I_3: dc.b $2
	dc.b $F0, $3, $20, $0, $0
	dc.b $F8, $1, $20, $4, $F8
DATAQP5EZUDB6I_4: dc.b $1
	dc.b $F0, $3, $20, $0, $F8
DATAQP5EZUDB6I_5: dc.b $2
	dc.b $F0, $3, $20, $0, $10
	dc.b $F8, $9, $20, $6, $F8
DATAQP5EZUDB6I_6: dc.b $4
	dc.b $F0, $D, $20, $0, $F0
	dc.b $0, $5, $20, $8, $0
	dc.b $FB, $5, $20, $C, $F5
	dc.b $0, $5, $20, $1C, $F0
DATAQP5EZUDB6I_7: dc.b $3
	dc.b $F6, $D, $20, $0, $EA
	dc.b $6, $5, $20, $8, $FA
	dc.b $0, $5, $20, $1C, $F0
DATAQP5EZUDB6I_8: dc.b $4
	dc.b $E7, $D, $20, $0, $F9
	dc.b $F7, $5, $20, $8, $9
	dc.b $F3, $B, $20, $10, $F5
	dc.b $0, $5, $20, $1C, $F0
	even