; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Aug 20 2020 10:18:11 GMT+0300 (RTZ 2 (зима))
; ================================================================================

DATABB1SFZCAF1R:
	dc.w DATABB1SFZCAF1R_0-DATABB1SFZCAF1R, DATABB1SFZCAF1R_1-DATABB1SFZCAF1R
	dc.w DATABB1SFZCAF1R_2-DATABB1SFZCAF1R, DATABB1SFZCAF1R_3-DATABB1SFZCAF1R
	dc.w DATABB1SFZCAF1R_4-DATABB1SFZCAF1R, DATABB1SFZCAF1R_5-DATABB1SFZCAF1R
	dc.w DATABB1SFZCAF1R_6-DATABB1SFZCAF1R, DATABB1SFZCAF1R_7-DATABB1SFZCAF1R
	dc.w DATABB1SFZCAF1R_8-DATABB1SFZCAF1R
DATABB1SFZCAF1R_0: dc.b $2
	dc.b $F8, $C, $0, $0, $F0
	dc.b $0, $4, $0, $4, $F8
DATABB1SFZCAF1R_1: dc.b $1
	dc.b $0, $C, $0, $0, $F0
DATABB1SFZCAF1R_2: dc.b $2
	dc.b $E8, $C, $0, $0, $F0
	dc.b $F0, $6, $0, $6, $F8
DATABB1SFZCAF1R_3: dc.b $2
	dc.b $F0, $3, $0, $0, $0
	dc.b $F8, $1, $0, $4, $F8
DATABB1SFZCAF1R_4: dc.b $1
	dc.b $F0, $3, $0, $0, $F8
DATABB1SFZCAF1R_5: dc.b $2
	dc.b $F0, $3, $0, $0, $10
	dc.b $F8, $9, $0, $6, $F8
DATABB1SFZCAF1R_6: dc.b $4
	dc.b $F0, $D, $0, $0, $F0
	dc.b $0, $5, $0, $8, $0
	dc.b $FB, $5, $0, $C, $F5
	dc.b $0, $5, $20, $1C, $F0
DATABB1SFZCAF1R_7: dc.b $3
	dc.b $F6, $D, $0, $0, $EA
	dc.b $6, $5, $0, $8, $FA
	dc.b $0, $5, $20, $1C, $F0
DATABB1SFZCAF1R_8: dc.b $4
	dc.b $E7, $D, $0, $0, $F9
	dc.b $F7, $5, $0, $8, $9
	dc.b $F3, $B, $0, $10, $F5
	dc.b $0, $5, $20, $1C, $F0
	even